---
abstract: 'Less indentation and newlines plus sub deparsing'
author:
  - 'mst - Matt S. Trout (cpan:MSTROUT) <mst@shadowcat.co.uk>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.2501, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Data-Dumper-Concise
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dumper: '0'
  Exporter: '0'
  perl: '5.006'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Data-Dumper-Concise
  repository: https://github.com/p5sagit/Data-Dumper-Concise.git
version: '2.023'
x_contributors:
  - "Arthur Axel 'fREW' Schmidt <frioux@gmail.com>"
  - 'Matt S Trout <matthewt@hercule.scsys.co.uk>'
  - 'Karen Etheridge <ether@cpan.org>'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
